services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    command:
      - start-dev
      - --verbose
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info,de.arbeitsagentur:trace
    ports:
      - "8080:8080"
    volumes:
      - ./target/providers:/opt/keycloak/providers:ro
      - ./src/test/resources/realm-wallet-demo-local.json:/opt/keycloak/data/import/realm-wallet-demo-local.json:ro
